version: "3.8"

services:
  backend:
    build: ./starwars-api
    container_name: starwars-backend
    ports:
      - "8080:8080"
    networks:
      - starwars-network
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./starwars-ui
    container_name: starwars-frontend
    ports:
      - "6969:80"
    networks:
      - starwars-network
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: starwars-db
    restart: always
    environment:
      POSTGRES_DB: starwars
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Abc123..
    ports:
      - "5432:5432"
    networks:
      - starwars-network

networks:
  starwars-network:
    driver: bridge
